site_name: LCCFQ Documentation
site_url: https://lccf-qhpc.github.io/lccfq-docs/


nav:
  - Home: index.md
  - Language:
    - Summary: language/summary.md
    - Overview: language/overview.md
  - Backend:
    - Architecture: backend/architecture.md
    - API Reference: backend/api_reference.md
  - Hardware Manager:
    - Summary: hw_manager/summary.md
  - About: about.md


theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - permalink
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
